### PR TITLE
doc: Add Javascript comment guidelines

### PR DESCRIPTION
**Pull request by helaan**

### CODE REVIEW

**Comment by bafonins** [comment]
Could you add an example of a **good** comment?

**Comment by helaan** [comment]
I intended this to be similar to the comment style used in my components, see Dropdown.js (#35) for an example. Should I add such an explanation in CONTRIBUTING.md?

**Comment by gwvdh** [comment]
Add Something about the props and authors

**Comment by HaicoDorenbos** [comment]
Sounds good

**Pull request merged**
